"""Rules/toolchains for angular with Bazel."""

module(
    name = "angular-cli",
)
bazel_dep(name = "bazel_skylib", version = "1.9.2")
bazel_dep(name = "rules_angular")
git_override(
    module_name = "rules_angular",
    commit = "5fa856469c642490a6e381a05d7f58f60fad1913",
    remote = "https://github.com/devversion/rules_angular.git",
)

bazel_dep(name = "devinfra")
git_override(
    module_name = "devinfra",
    commit = "cde7ad16c16f5c7dbd57b62e8b930443813484ec",
    remote = "https://github.com/angular/dev-infra.git",
)
